
services:
  configserver:
    image: nower/bankapp-configserver:latest
    ports:
      - "8071:8071"
    networks:
      - bankapp-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  account:
    image: nower/bankapp:latest
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp-network
    depends_on:
      configserver:
        condition: service_healthy

  cards:
    image: nower/bankapp-cards:latest
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp-network
    depends_on:
      configserver:
        condition: service_healthy

  loans:
    image: nower/bankapp-loans:latest
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bankapp-network
    depends_on:
      configserver:
        condition: service_healthy


networks:
  bankapp-network:
    driver: bridge
